[tox]
envlist = py{310,311,312,313,314}, py312-functional, ruff-check, ruff, mypy, begin, end
skip_missing_interpreters = true

[testenv]
package = wheel
set_env =
    PACKAGE_NAME = exordos_paas_mail
    TEST_PATH = exordos_paas_mail/tests/unit
passenv = HOME NO_PROXY HTTP_PROXY HTTPS_PROXY ALL_PROXY
deps =
    -e .[test]
    pytest-cov
commands =
    coverage run -m pytest {posargs:exordos_paas_mail/tests/unit}
    coverage report

[testenv:py{310,311,312,313,314}-functional]
passenv =
    HOME NO_PROXY HTTP_PROXY HTTPS_PROXY ALL_PROXY
    EXORDOS_* METAPAAS_*
setenv =
    TEST_PATH = exordos_paas_mail/tests/functional
deps =
    -e .[test]
commands =
    pytest {posargs:exordos_paas_mail/tests/functional}

[testenv:begin]
skip_install = true
deps = coverage[toml]
commands = coverage erase

[testenv:end]
skip_install = true
deps = coverage[toml]
commands =
    coverage combine
    coverage report
    coverage html
    coverage xml

[testenv:ruff]
skip_install = true
deps = ruff
commands = ruff format exordos_paas_mail

[testenv:ruff-check]
skip_install = true
deps = ruff
commands = ruff check exordos_paas_mail

[testenv:mypy]
deps =
    -e .[dev]
commands = mypy exordos_paas_mail
