#    Copyright 2026 Genesis Corporation.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
from __future__ import annotations

import logging
import os
import re
import subprocess

from gcl_sdk.agents.universal import constants as c
from gcl_sdk.agents.universal.drivers import meta
from gcl_sdk.infra import constants as pc
from restalchemy.dm import properties
from restalchemy.dm import types as ra_types

from exordos_mail import constants

LOG = logging.getLogger(__name__)


def _write_file_atomic(path: str, content: str) -> bool:
    """Write file; return True if content changed."""
    try:
        with open(path, "r") as f:
            existing = f.read()
        if existing == content:
            return False
    except FileNotFoundError:
        pass

    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
    os.rename(tmp, path)
    return True


def _reload_exim4() -> None:
    try:
        subprocess.run(["systemctl", "reload", "exim4"], check=True, timeout=10)
        LOG.info("exim4 reloaded")
    except Exception:
        LOG.warning("Failed to reload exim4; attempting restart", exc_info=True)
        subprocess.run(["systemctl", "restart", "exim4"], timeout=30)


class MailInstance(meta.MetaDataPlaneModel):
    """Data plane model for a single exim4 SMTP node (genesis_sender pattern).

    Reconciles target account state (from control plane) with the local
    exim4 passwd file for SMTP AUTH:
      - /etc/exim4/passwd — lsearch format: username@domain:crypt_hash
    Hashes are stored as raw crypt format ($6$...), Dovecot prefixes stripped.
    """

    name = properties.property(
        ra_types.String(min_length=1, max_length=512),
        required=True,
    )
    domain = properties.property(
        ra_types.String(min_length=1, max_length=255),
        required=True,
    )
    accounts = properties.property(ra_types.Dict(), default=dict)
    status = properties.property(
        ra_types.Enum([s.value for s in pc.InstanceStatus]),
        default=pc.InstanceStatus.ACTIVE.value,
    )
    # DKIM facts discovered on the data plane (generated by the configure
    # script). Reported back to the control plane so the public key can be
    # published in DNS. Not part of the meta fields — always read from disk.
    dkim_public_key = properties.property(ra_types.String(max_length=4096), default="")
    dkim_selector = properties.property(ra_types.String(max_length=255), default="")

    _meta_fields = {"uuid", "name", "domain"}

    def get_meta_model_fields(self) -> set[str] | None:
        return self._meta_fields

    # ------------------------------------------------------------------
    # exim4 passwd file  (SMTP AUTH — lsearch lookup by username@domain)
    # Format: username@domain:crypt_hash
    # exim4 crypteq understands $6$/5$/1$ directly — not {SHA512-CRYPT} prefix.
    # ------------------------------------------------------------------

    @staticmethod
    def _strip_dovecot_prefix(password_hash: str) -> str:
        """Strip Dovecot scheme prefix (e.g. {SHA512-CRYPT}) that exim4 doesn't understand."""
        if password_hash.startswith("{") and "}" in password_hash:
            return password_hash[password_hash.index("}") + 1 :]
        return password_hash

    def _build_exim4_passwd(self) -> str:
        lines = []
        for username, info in self.accounts.items():
            if not info.get("active", True):
                continue
            password_hash = self._strip_dovecot_prefix(info.get("password_hash", ""))
            lines.append(f"{username}@{self.domain}:{password_hash}")
        return "\n".join(lines) + "\n" if lines else ""

    # ------------------------------------------------------------------
    # DKIM public key  (read-only fact; generated once by configure script)
    # opendkim-genkey writes platform.txt as a BIND TXT record with the key
    # split across several quoted chunks, e.g.:
    #   platform._domainkey IN TXT ( "v=DKIM1; h=sha256; k=rsa; "
    #     "p=MIGfMA0...AB" )  ; ----- DKIM key platform for example.com
    # Concatenating the quoted chunks yields the value to publish in DNS.
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_dkim_txt(content: str) -> str:
        chunks = re.findall(r'"([^"]*)"', content)
        return "".join(chunks).strip()

    def _read_dkim_public_key(self) -> str:
        try:
            with open(constants.EXIM4_DKIM_TXT_FILE) as f:
                return self._parse_dkim_txt(f.read())
        except FileNotFoundError:
            return ""

    def _read_exim4_passwd(self) -> dict:
        result = {}
        try:
            with open(constants.EXIM4_PASSWD_FILE) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    parts = line.split(":")
                    if len(parts) >= 2:
                        result[parts[0]] = line
        except FileNotFoundError:
            pass
        return result

    # -- MetaDataPlaneModel interface --

    def dump_to_dp(self) -> None:
        exim4_changed = _write_file_atomic(
            constants.EXIM4_PASSWD_FILE, self._build_exim4_passwd()
        )
        if exim4_changed:
            _reload_exim4()

    def restore_from_dp(self) -> None:
        actual = self._read_exim4_passwd()
        self.accounts = {}
        for full_addr in actual:
            if "@" in full_addr:
                local = full_addr.split("@")[0]
                self.accounts[local] = {
                    "password_hash": "",
                    "active": True,
                }
        self.dkim_public_key = self._read_dkim_public_key()
        self.dkim_selector = constants.DKIM_SELECTOR if self.dkim_public_key else ""

    def delete_from_dp(self) -> None:
        pass

    def update_on_dp(self) -> None:
        self.dump_to_dp()


class MailCapabilityDriver(meta.MetaFileStorageAgentDriver):
    """Mail capability driver for the universal agent."""

    MAIL_META_PATH = os.path.join(c.WORK_DIR, "mail_meta.json")

    __model_map__ = {
        "mail_instance_node": MailInstance,
    }

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, meta_file=self.MAIL_META_PATH, **kwargs)
